missions=[
    {
        name:'',
        background:0,level:0,zone:0,
        player:{type:1,primary:5,secondary:2,passive:1,body:1,direction:0,team:0,name:['Duckipo']},
        ally:[
            {type:0,primary:0,secondary:0,passive:0,body:1,direction:0,team:0,number:0,name:[]}
        ],
        other:[
            {
                position:{x:60,y:60},group:[
                    {type:0,primary:0,secondary:0,passive:0,body:0,direction:0,team:1,number:0}
                ]
            },
        ]
    },{
        name:'Select',
        background:0,level:0,zone:1,
        player:{type:0,primary:0,secondary:0,passive:0,body:1,direction:0,team:0,name:['Duckipo']},
        ally:[],
        other:[],
    },{
        name:'Gangfight',
        background:1,level:1,zone:0,
        player:{type:4,primary:4,secondary:2,passive:0,body:1,direction:0,team:2,name:['Duckipo']},
        ally:[
            {type:4,primary:4,secondary:2,passive:0,body:1,direction:0,team:2,number:2,name:['Dippy','Dukep']}
        ],
        other:[
            {
                position:{x:440,y:160},group:[
                    {type:4,primary:4,secondary:0,passive:0,body:1,direction:180,team:3,number:2}
                ],
            },
        ]
    },
    
    
    
    /*{
        name:'Ordinary Routine',
        background:0,level:0,zone:0,
        player:{type:1,primary:1,secondary:0,passive:1,body:1,direction:0,team:0,name:['Duckipo']},
        ally:[
            {type:1,primary:1,secondary:0,passive:0,body:1,direction:0,team:0,number:2,name:['Dippy','Dukep']}
        ],
        other:[
            {
                position:{x:60,y:60},group:[
                    {type:1,primary:1,secondary:0,passive:0,body:0,direction:0,team:1,number:3}
                ],
            },
        ]
    },{
        name:'',
        background:0,level:0,zone:0,
        player:{type:1,primary:5,secondary:3,passive:1,body:1,direction:0,team:0,name:['Duckipo']},
        ally:[
            {type:0,primary:0,secondary:0,passive:0,body:1,direction:0,team:0,number:0,name:[]}
        ],
        other:[
            {
                position:{x:60,y:60},group:[
                    {type:0,primary:0,secondary:0,passive:0,body:0,direction:0,team:1,number:1}
                ],
            },
        ]
    },*/
]