types={
    projectile:[
        {
            name:'Beam',
            damage:20,speed:10,size:3,
            image:1,
        },
    ],troop:[
        {
            name:'Unarmed',
            life:100,speed:3,size:15,turnSpeed:10,
            reload:0,projectile:0,spread:0,spawn:{x:0,y:0},
            recoil:{loop:0,anim:0,speed:0,return:0},
        },{
            name:'Pistol',
            life:120,speed:2,size:15,turnSpeed:6,
            reload:30,projectile:0,spread:5,spawn:{x:12,y:-20},
            recoil:{loop:1,anim:3,speed:1,return:0.2},
        },
    ],team:[
        {
            color:[[50,255,50],[100,255,100]],
        },{
            color:[[50,50,255],[100,100,255]],
        },
    ]
}
dev={mark:true}
stage={scale:0,focus:{x:0,y:0,scale:0},scene:'level',background:0}
game={level:0,zone:0,mission:0,edge:{x:0,y:0},player:{team:0,alive:false},tileSize:40}
physics={resistance:0.05,friction:0.025}
graphics={main:0,backgrounds:[],minor:[]}
transition={trigger:false,anim:0,scene:stage.scene}
inputs={mouse:{x:0,y:0},screen:{x:0,y:0},rel:{x:0,y:0},keys:[[false,false,false,false],[false,false,false,false]]}
entities={projectiles:[],walls:[],troops:[],particles:[]}
collision={incident:{x:0,y:0},calculate:{x:0,y:0}}
calc={int:[0,0]}
run={fore:[],info:[]}
a=0;b=0;c=0;d=0;_=0
la=0;lb=0;lc=0;ld=0